name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:          
    - uses: actions/checkout@v3
   
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{secret.DOCKERHUB_USERNAME}}
        password: ${{secret.DOCKERHUB_PASSWORD}}
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.1.0
      with:
        file: ./Dockerfile
        push: true
        tags: ${{secret.DOCKER_IMAGE}}
    - run: ls -la
        
            
         
            
